package mod.beethoven92.betterendforge.common.recipes;

import mod.beethoven92.betterendforge.common.init.ModBlocks;
import mod.beethoven92.betterendforge.common.init.ModItems;
import net.minecraft.block.Blocks;
import net.minecraft.enchantment.Enchantment;
import net.minecraft.enchantment.EnchantmentData;
import net.minecraft.enchantment.Enchantments;
import net.minecraft.item.EnchantedBookItem;
import net.minecraft.item.ItemStack;
import net.minecraft.item.Items;

// Defines special recipes that cannot be handled by jsons
// TODO: Move this to json now that output item can have NBT
public class SpecialInfusionRecipes
{
	public static void createRecipes()
	{
		InfusionRecipe.Builder.create("protection_book").
        setInput(Items.BOOK).
        setOutput(createEnchantedBook(Enchantments.PROTECTION, 1)).
        setTime(300).
        addCatalyst(0, ModItems.ENCHANTED_PETAL.get()).
        addCatalyst(4, Items.TURTLE_HELMET).
        addCatalyst(1, Items.LAPIS_LAZULI).
        addCatalyst(3, Items.LAPIS_LAZULI).
        addCatalyst(5, Items.LAPIS_LAZULI).
        addCatalyst(7, Items.LAPIS_LAZULI).
        build();
		
		InfusionRecipe.Builder.create("fire_protection_book")
		.setInput(Items.BOOK)
		.setOutput(createEnchantedBook(Enchantments.FIRE_PROTECTION, 1))
		.addCatalyst(0, ModItems.ENCHANTED_PETAL.get())
		.addCatalyst(2, Items.BLAZE_ROD)
		.addCatalyst(4, Items.BLAZE_ROD)
		.addCatalyst(6, Items.BLAZE_ROD)
		.addCatalyst(1, Items.LAPIS_LAZULI)
		.addCatalyst(3, Items.LAPIS_LAZULI)
		.addCatalyst(5, Items.LAPIS_LAZULI)
		.addCatalyst(7, Items.LAPIS_LAZULI)
		.setGroup("enchantment")
		.setTime(300)
		.build();
	     
		InfusionRecipe.Builder.create("feather_falling_book")
		.setInput(Items.BOOK)
		.setOutput(createEnchantedBook(Enchantments.FEATHER_FALLING, 1))
		.addCatalyst(0, ModItems.ENCHANTED_PETAL.get())
		.addCatalyst(2, Items.FEATHER)
		.addCatalyst(4, Items.FEATHER)
		.addCatalyst(6, Items.FEATHER)
		.addCatalyst(1, Items.LAPIS_LAZULI)
		.addCatalyst(3, Items.LAPIS_LAZULI)
		.addCatalyst(5, Items.LAPIS_LAZULI)
		.addCatalyst(7, Items.LAPIS_LAZULI)
		.setGroup("enchantment")
		.setTime(300)
		.build();
	     
		InfusionRecipe.Builder.create("blast_protection_book")
		.setInput(Items.BOOK)
		.setOutput(createEnchantedBook(Enchantments.BLAST_PROTECTION, 1))
		.addCatalyst(0, ModItems.ENCHANTED_PETAL.get())
		.addCatalyst(2, Blocks.OBSIDIAN)
		.addCatalyst(4, Blocks.OBSIDIAN)
		.addCatalyst(6, Blocks.OBSIDIAN)
		.addCatalyst(1, Items.LAPIS_LAZULI)
		.addCatalyst(3, Items.LAPIS_LAZULI)
		.addCatalyst(5, Items.LAPIS_LAZULI)
		.addCatalyst(7, Items.LAPIS_LAZULI)
		.setGroup("enchantment")
		.setTime(300)
		.build();
	    
		InfusionRecipe.Builder.create("projectile_protection_book")
		.setInput(Items.BOOK)
		.setOutput(createEnchantedBook(Enchantments.PROJECTILE_PROTECTION, 1))
		.addCatalyst(0, ModItems.ENCHANTED_PETAL.get())
		.addCatalyst(2, Items.SCUTE)
		.addCatalyst(4, Items.SHIELD)
		.addCatalyst(6, Items.SCUTE)
		.addCatalyst(1, Items.LAPIS_LAZULI)
		.addCatalyst(3, Items.LAPIS_LAZULI)
		.addCatalyst(5, Items.LAPIS_LAZULI)
		.addCatalyst(7, Items.LAPIS_LAZULI)
		.setGroup("enchantment")
		.setTime(300)
		.build();
	    
		InfusionRecipe.Builder.create("respiration_book")
		.setInput(Items.BOOK)
		.setOutput(createEnchantedBook(Enchantments.RESPIRATION, 1))
		.addCatalyst(0, ModItems.ENCHANTED_PETAL.get())
		.addCatalyst(2, Items.NAUTILUS_SHELL)
		.addCatalyst(4, Items.NAUTILUS_SHELL)
		.addCatalyst(6, Items.NAUTILUS_SHELL)
		.addCatalyst(1, Items.LAPIS_LAZULI)
		.addCatalyst(3, Items.LAPIS_LAZULI)
		.addCatalyst(5, Items.LAPIS_LAZULI)
		.addCatalyst(7, Items.LAPIS_LAZULI)
		.setGroup("enchantment")
		.setTime(300)
		.build();
	    
		InfusionRecipe.Builder.create("aqua_affinity_book")
		.setInput(Items.BOOK)
		.setOutput(createEnchantedBook(Enchantments.AQUA_AFFINITY, 1))
		.addCatalyst(0, ModItems.ENCHANTED_PETAL.get())
		.addCatalyst(2, Items.PRISMARINE_CRYSTALS)
		.addCatalyst(4, Items.PRISMARINE_CRYSTALS)
		.addCatalyst(6, Items.PRISMARINE_CRYSTALS)
		.addCatalyst(1, Items.LAPIS_LAZULI)
		.addCatalyst(3, Items.LAPIS_LAZULI)
		.addCatalyst(5, Items.LAPIS_LAZULI)
		.addCatalyst(7, Items.LAPIS_LAZULI)
		.setGroup("enchantment")
		.setTime(300)
		.build();
	    
		InfusionRecipe.Builder.create("thorns_book")
		.setInput(Items.BOOK)
		.setOutput(createEnchantedBook(Enchantments.THORNS, 1))
		.addCatalyst(0, ModItems.ENCHANTED_PETAL.get())
		.addCatalyst(2, Blocks.CACTUS)
		.addCatalyst(4, Blocks.CACTUS)
		.addCatalyst(6, Blocks.CACTUS)
		.addCatalyst(1, Items.LAPIS_LAZULI)
		.addCatalyst(3, Items.LAPIS_LAZULI)
		.addCatalyst(5, Items.LAPIS_LAZULI)
		.addCatalyst(7, Items.LAPIS_LAZULI)
		.setGroup("enchantment")
		.setTime(300)
		.build();
	    
		InfusionRecipe.Builder.create("depth_strider_book")
		.setInput(Items.BOOK)
		.setOutput(createEnchantedBook(Enchantments.DEPTH_STRIDER, 1))
		.addCatalyst(0, ModItems.ENCHANTED_PETAL.get())
		.addCatalyst(2, Blocks.LILY_PAD)
		.addCatalyst(4, ModBlocks.END_LILY_SEED.get())
		.addCatalyst(6, Blocks.LILY_PAD)
		.addCatalyst(1, Items.LAPIS_LAZULI)
		.addCatalyst(3, Items.LAPIS_LAZULI)
		.addCatalyst(5, Items.LAPIS_LAZULI)
		.addCatalyst(7, Items.LAPIS_LAZULI)
		.setGroup("enchantment")
		.setTime(300)
		.build();
	    
		InfusionRecipe.Builder.create("frost_walker_book")
		.setInput(Items.BOOK)
		.setOutput(createEnchantedBook(Enchantments.FROST_WALKER, 1))
		.addCatalyst(0, ModItems.ENCHANTED_PETAL.get())
		.addCatalyst(4, ModBlocks.ANCIENT_EMERALD_ICE.get())
		.addCatalyst(1, Items.LAPIS_LAZULI)
		.addCatalyst(3, Items.LAPIS_LAZULI)
		.addCatalyst(5, Items.LAPIS_LAZULI)
		.addCatalyst(7, Items.LAPIS_LAZULI)
		.setGroup("enchantment")
		.setTime(300)
		.build();
	    
		InfusionRecipe.Builder.create("soul_speed_book")
		.setInput(Items.BOOK)
		.setOutput(createEnchantedBook(Enchantments.SOUL_SPEED, 1))
		.addCatalyst(0, ModItems.ENCHANTED_PETAL.get())
		.addCatalyst(2, Blocks.SOUL_SAND, Blocks.SOUL_SOIL)
		.addCatalyst(4, Blocks.SOUL_SAND, Blocks.SOUL_SOIL)
		.addCatalyst(6, Blocks.SOUL_SAND, Blocks.SOUL_SOIL)
		.addCatalyst(1, Items.LAPIS_LAZULI)
		.addCatalyst(3, Items.LAPIS_LAZULI)
		.addCatalyst(5, Items.LAPIS_LAZULI)
		.addCatalyst(7, Items.LAPIS_LAZULI)
		.setGroup("enchantment")
		.setTime(300)
		.build();
	    
		InfusionRecipe.Builder.create("sharpness_book")
		.setInput(Items.BOOK)
		.setOutput(createEnchantedBook(Enchantments.SHARPNESS, 1))
		.addCatalyst(0, ModItems.ENCHANTED_PETAL.get())
		.addCatalyst(4, Items.NETHERITE_SCRAP)
		.addCatalyst(1, Items.LAPIS_LAZULI)
		.addCatalyst(3, Items.LAPIS_LAZULI)
		.addCatalyst(5, Items.LAPIS_LAZULI)
		.addCatalyst(7, Items.LAPIS_LAZULI)
		.setGroup("enchantment")
		.setTime(300)
		.build();
	    
		InfusionRecipe.Builder.create("smite_book")
		.setInput(Items.BOOK)
		.setOutput(createEnchantedBook(Enchantments.SMITE, 1))
		.addCatalyst(0, ModItems.ENCHANTED_PETAL.get())
		.addCatalyst(2, Blocks.SUNFLOWER)
		.addCatalyst(4, Items.GOLD_INGOT)
		.addCatalyst(6, Blocks.SUNFLOWER)
		.addCatalyst(1, Items.LAPIS_LAZULI)
		.addCatalyst(3, Items.LAPIS_LAZULI)
		.addCatalyst(5, Items.LAPIS_LAZULI)
		.addCatalyst(7, Items.LAPIS_LAZULI)
		.setGroup("enchantment")
		.setTime(300)
		.build();
	    
		InfusionRecipe.Builder.create("bane_of_arthropods_book")
		.setInput(Items.BOOK)
		.setOutput(createEnchantedBook(Enchantments.BANE_OF_ARTHROPODS, 1))
		.addCatalyst(0, ModItems.ENCHANTED_PETAL.get())
		.addCatalyst(2, Items.FERMENTED_SPIDER_EYE)
		.addCatalyst(4, Items.IRON_INGOT)
		.addCatalyst(6, Items.FERMENTED_SPIDER_EYE)
		.addCatalyst(1, Items.LAPIS_LAZULI)
		.addCatalyst(3, Items.LAPIS_LAZULI)
		.addCatalyst(5, Items.LAPIS_LAZULI)
		.addCatalyst(7, Items.LAPIS_LAZULI)
		.setGroup("enchantment")
		.setTime(300)
		.build();
	    
		InfusionRecipe.Builder.create("knockback_book")
		.setInput(Items.BOOK)
		.setOutput(createEnchantedBook(Enchantments.KNOCKBACK, 1))
		.addCatalyst(0, ModItems.ENCHANTED_PETAL.get())
		.addCatalyst(2, Items.REDSTONE)
		.addCatalyst(4, Blocks.PISTON)
		.addCatalyst(6, Items.REDSTONE)
		.addCatalyst(1, Items.LAPIS_LAZULI)
		.addCatalyst(3, Items.LAPIS_LAZULI)
		.addCatalyst(5, Items.LAPIS_LAZULI)
		.addCatalyst(7, Items.LAPIS_LAZULI)
		.setGroup("enchantment")
		.setTime(300)
		.build();
	    
		InfusionRecipe.Builder.create("fire_aspect_book")
		.setInput(Items.BOOK)
		.setOutput(createEnchantedBook(Enchantments.FIRE_ASPECT, 1))
		.addCatalyst(0, ModItems.ENCHANTED_PETAL.get())
		.addCatalyst(2, Items.BLAZE_POWDER)
		.addCatalyst(4, Items.MAGMA_CREAM)
		.addCatalyst(6, Items.BLAZE_POWDER)
		.addCatalyst(1, Items.LAPIS_LAZULI)
		.addCatalyst(3, Items.LAPIS_LAZULI)
		.addCatalyst(5, Items.LAPIS_LAZULI)
		.addCatalyst(7, Items.LAPIS_LAZULI)
		.setGroup("enchantment")
		.setTime(300)
		.build();
	    
		InfusionRecipe.Builder.create("looting_book")
		.setInput(Items.BOOK)
		.setOutput(createEnchantedBook(Enchantments.LOOTING, 1))
		.addCatalyst(0, ModItems.ENCHANTED_PETAL.get())
		.addCatalyst(2, Items.EMERALD)
		.addCatalyst(4, Items.GOLD_INGOT)
		.addCatalyst(6, Items.EMERALD)
		.addCatalyst(1, Items.LAPIS_LAZULI)
		.addCatalyst(3, Items.LAPIS_LAZULI)
		.addCatalyst(5, Items.LAPIS_LAZULI)
		.addCatalyst(7, Items.LAPIS_LAZULI)
		.setGroup("enchantment")
		.setTime(300)
		.build();
	    
		InfusionRecipe.Builder.create("sweeping_book")
		.setInput(Items.BOOK)
		.setOutput(createEnchantedBook(Enchantments.SWEEPING, 1))
		.addCatalyst(0, ModItems.ENCHANTED_PETAL.get())
		.addCatalyst(2, Items.GOLDEN_SWORD)
		.addCatalyst(4, Items.IRON_SWORD)
		.addCatalyst(6, Items.GOLDEN_SWORD)
		.addCatalyst(1, Items.LAPIS_LAZULI)
		.addCatalyst(3, Items.LAPIS_LAZULI)
		.addCatalyst(5, Items.LAPIS_LAZULI)
		.addCatalyst(7, Items.LAPIS_LAZULI)
		.setGroup("enchantment")
		.setTime(300)
		.build();
	    
		InfusionRecipe.Builder.create("efficiency_book")
		.setInput(Items.BOOK)
		.setOutput(createEnchantedBook(Enchantments.EFFICIENCY, 1))
		.addCatalyst(0, ModItems.ENCHANTED_PETAL.get())
		.addCatalyst(2, ModItems.AMBER_GEM.get())
		.addCatalyst(4, ModItems.AMBER_GEM.get())
		.addCatalyst(6, ModItems.AMBER_GEM.get())
		.addCatalyst(1, Items.LAPIS_LAZULI)
		.addCatalyst(3, Items.LAPIS_LAZULI)
		.addCatalyst(5, Items.LAPIS_LAZULI)
		.addCatalyst(7, Items.LAPIS_LAZULI)
		.setGroup("enchantment")
		.setTime(300)
		.build();
	    
		InfusionRecipe.Builder.create("silk_touch_book")
		.setInput(Items.BOOK)
		.setOutput(createEnchantedBook(Enchantments.SILK_TOUCH, 1))
		.addCatalyst(0, ModItems.ENCHANTED_PETAL.get())
		.addCatalyst(2, Blocks.COBWEB)
		.addCatalyst(4, ModItems.ETERNAL_CRYSTAL.get())
		.addCatalyst(6, Blocks.COBWEB)
		.addCatalyst(1, Items.LAPIS_LAZULI)
		.addCatalyst(3, Items.LAPIS_LAZULI)
		.addCatalyst(5, Items.LAPIS_LAZULI)
		.addCatalyst(7, Items.LAPIS_LAZULI)
		.setGroup("enchantment")
		.setTime(375)
		.build();
	    
		InfusionRecipe.Builder.create("unbreaking_book")
		.setInput(Items.BOOK)
		.setOutput(createEnchantedBook(Enchantments.UNBREAKING, 1))
		.addCatalyst(0, ModItems.ENCHANTED_PETAL.get())
		.addCatalyst(2, Items.DIAMOND)
		.addCatalyst(4, Items.DIAMOND)
		.addCatalyst(6, Items.DIAMOND)
		.addCatalyst(1, Items.LAPIS_LAZULI)
		.addCatalyst(3, Items.LAPIS_LAZULI)
		.addCatalyst(5, Items.LAPIS_LAZULI)
		.addCatalyst(7, Items.LAPIS_LAZULI)
		.setGroup("enchantment")
		.setTime(300)
		.build();
	    
		InfusionRecipe.Builder.create("fortune_book")
		.setInput(Items.BOOK)
		.setOutput(createEnchantedBook(Enchantments.FORTUNE, 1))
		.addCatalyst(0, ModItems.ENCHANTED_PETAL.get())
		.addCatalyst(2, Items.EMERALD)
		.addCatalyst(4, Items.RABBIT_FOOT)
		.addCatalyst(6, Items.EMERALD)
		.addCatalyst(1, Items.LAPIS_LAZULI)
		.addCatalyst(3, Items.LAPIS_LAZULI)
		.addCatalyst(5, Items.LAPIS_LAZULI)
		.addCatalyst(7, Items.LAPIS_LAZULI)
		.setGroup("enchantment")
		.setTime(300)
		.build();
	    
		InfusionRecipe.Builder.create("power_book")
		.setInput(Items.BOOK)
		.setOutput(createEnchantedBook(Enchantments.POWER, 1))
		.addCatalyst(0, ModItems.ENCHANTED_PETAL.get())
		.addCatalyst(2, ModItems.AMBER_GEM.get())
		.addCatalyst(4, Items.DIAMOND_SWORD)
		.addCatalyst(6, ModItems.AMBER_GEM.get())
		.addCatalyst(1, Items.LAPIS_LAZULI)
		.addCatalyst(3, Items.LAPIS_LAZULI)
		.addCatalyst(5, Items.LAPIS_LAZULI)
		.addCatalyst(7, Items.LAPIS_LAZULI)
		.setGroup("enchantment")
		.setTime(300)
		.build();
	    
		InfusionRecipe.Builder.create("punch_book")
		.setInput(Items.BOOK)
		.setOutput(createEnchantedBook(Enchantments.PUNCH, 1))
		.addCatalyst(0, ModItems.ENCHANTED_PETAL.get())
		.addCatalyst(2, Items.POPPED_CHORUS_FRUIT)
		.addCatalyst(4, Items.SPECTRAL_ARROW)
		.addCatalyst(6, Items.POPPED_CHORUS_FRUIT)
		.addCatalyst(1, Items.LAPIS_LAZULI)
		.addCatalyst(3, Items.LAPIS_LAZULI)
		.addCatalyst(5, Items.LAPIS_LAZULI)
		.addCatalyst(7, Items.LAPIS_LAZULI)
		.setGroup("enchantment")
		.setTime(300)
		.build();
	    
		InfusionRecipe.Builder.create("flame_book")
		.setInput(Items.BOOK)
		.setOutput(createEnchantedBook(Enchantments.FLAME, 1))
		.addCatalyst(0, ModItems.ENCHANTED_PETAL.get())
		.addCatalyst(2, Items.BLAZE_POWDER)
		.addCatalyst(4, Items.SPECTRAL_ARROW)
		.addCatalyst(6, Items.BLAZE_POWDER)
		.addCatalyst(1, Items.LAPIS_LAZULI)
		.addCatalyst(3, Items.LAPIS_LAZULI)
		.addCatalyst(5, Items.LAPIS_LAZULI)
		.addCatalyst(7, Items.LAPIS_LAZULI)
		.setGroup("enchantment")
		.setTime(300)
		.build();
	    
		InfusionRecipe.Builder.create("infinity_book")
		.setInput(Items.BOOK)
		.setOutput(createEnchantedBook(Enchantments.INFINITY, 1))
		.addCatalyst(0, ModItems.ENCHANTED_PETAL.get())
		.addCatalyst(2, Items.SPECTRAL_ARROW)
		.addCatalyst(4, ModItems.ETERNAL_CRYSTAL.get())
		.addCatalyst(6, Items.SPECTRAL_ARROW)
		.addCatalyst(1, Items.LAPIS_LAZULI)
		.addCatalyst(3, Items.LAPIS_LAZULI)
		.addCatalyst(5, Items.LAPIS_LAZULI)
		.addCatalyst(7, Items.LAPIS_LAZULI)
		.setGroup("enchantment")
		.setTime(375)
		.build();
	    
		InfusionRecipe.Builder.create("luck_of_sea_book")
		.setInput(Items.BOOK)
		.setOutput(createEnchantedBook(Enchantments.LUCK_OF_THE_SEA, 1))
		.addCatalyst(0, ModItems.ENCHANTED_PETAL.get())
		.addCatalyst(2, Items.EMERALD)
		.addCatalyst(4, Items.FISHING_ROD)
		.addCatalyst(6, Items.EMERALD)
		.addCatalyst(1, Items.LAPIS_LAZULI)
		.addCatalyst(3, Items.LAPIS_LAZULI)
		.addCatalyst(5, Items.LAPIS_LAZULI)
		.addCatalyst(7, Items.LAPIS_LAZULI)
		.setGroup("enchantment")
		.setTime(300)
		.build();
	    
		InfusionRecipe.Builder.create("lure_book")
		.setInput(Items.BOOK)
		.setOutput(createEnchantedBook(Enchantments.LURE, 1))
		.addCatalyst(0, ModItems.ENCHANTED_PETAL.get())
		.addCatalyst(2, Items.GOLD_NUGGET)
		.addCatalyst(4, Items.FISHING_ROD)
		.addCatalyst(6, Items.GOLD_NUGGET)
		.addCatalyst(1, Items.LAPIS_LAZULI)
		.addCatalyst(3, Items.LAPIS_LAZULI)
		.addCatalyst(5, Items.LAPIS_LAZULI)
		.addCatalyst(7, Items.LAPIS_LAZULI)
		.setGroup("enchantment")
		.setTime(300)
		.build();
	    
		InfusionRecipe.Builder.create("loyalty_book")
		.setInput(Items.BOOK)
		.setOutput(createEnchantedBook(Enchantments.LOYALTY, 1))
		.addCatalyst(0, ModItems.ENCHANTED_PETAL.get())
		.addCatalyst(2, Items.ENDER_EYE)
		.addCatalyst(4, Items.HEART_OF_THE_SEA)
		.addCatalyst(6, Items.ENDER_EYE)
		.addCatalyst(1, Items.LAPIS_LAZULI)
		.addCatalyst(3, Items.LAPIS_LAZULI)
		.addCatalyst(5, Items.LAPIS_LAZULI)
		.addCatalyst(7, Items.LAPIS_LAZULI)
		.setGroup("enchantment")
		.setTime(375)
		.build();
	    
		InfusionRecipe.Builder.create("impaling_book")
		.setInput(Items.BOOK)
		.setOutput(createEnchantedBook(Enchantments.IMPALING, 1))
		.addCatalyst(0, ModItems.ENCHANTED_PETAL.get())
		.addCatalyst(2, Items.PRISMARINE_SHARD)
		.addCatalyst(4, Items.IRON_SWORD)
		.addCatalyst(6, Items.PRISMARINE_SHARD)
		.addCatalyst(1, Items.LAPIS_LAZULI)
		.addCatalyst(3, Items.LAPIS_LAZULI)
		.addCatalyst(5, Items.LAPIS_LAZULI)
		.addCatalyst(7, Items.LAPIS_LAZULI)
		.setGroup("enchantment")
		.setTime(300)
		.build();
	    
		InfusionRecipe.Builder.create("riptide_book")
		.setInput(Items.BOOK)
		.setOutput(createEnchantedBook(Enchantments.RIPTIDE, 1))
		.addCatalyst(0, ModItems.ENCHANTED_PETAL.get())
		.addCatalyst(2, Items.LEAD)
		.addCatalyst(4, Items.HEART_OF_THE_SEA)
		.addCatalyst(6, Items.LEAD)
		.addCatalyst(1, Items.LAPIS_LAZULI)
		.addCatalyst(3, Items.LAPIS_LAZULI)
		.addCatalyst(5, Items.LAPIS_LAZULI)
		.addCatalyst(7, Items.LAPIS_LAZULI)
		.setGroup("enchantment")
		.setTime(375)
		.build();
	    
		InfusionRecipe.Builder.create("channeling_book")
		.setInput(Items.BOOK)
		.setOutput(createEnchantedBook(Enchantments.CHANNELING, 1))
		.addCatalyst(0, ModItems.ENCHANTED_PETAL.get())
		.addCatalyst(2, Items.CHAIN)
		.addCatalyst(4, Items.HEART_OF_THE_SEA)
		.addCatalyst(6, Items.CHAIN)
		.addCatalyst(1, Items.LAPIS_LAZULI)
		.addCatalyst(3, Items.LAPIS_LAZULI)
		.addCatalyst(5, Items.LAPIS_LAZULI)
		.addCatalyst(7, Items.LAPIS_LAZULI)
		.setGroup("enchantment")
		.setTime(375)
		.build();
	    
		InfusionRecipe.Builder.create("multishot_book")
		.setInput(Items.BOOK)
		.setOutput(createEnchantedBook(Enchantments.MULTISHOT, 1))
		.addCatalyst(0, ModItems.ENCHANTED_PETAL.get())
		.addCatalyst(2, Items.ARROW)
		.addCatalyst(4, Items.SPECTRAL_ARROW)
		.addCatalyst(6, Items.ARROW)
		.addCatalyst(1, Items.LAPIS_LAZULI)
		.addCatalyst(3, Items.LAPIS_LAZULI)
		.addCatalyst(5, Items.LAPIS_LAZULI)
		.addCatalyst(7, Items.LAPIS_LAZULI)
		.setGroup("enchantment")
		.setTime(300)
		.build();
	    
		InfusionRecipe.Builder.create("quick_charge_book")
		.setInput(Items.BOOK)
		.setOutput(createEnchantedBook(Enchantments.QUICK_CHARGE, 1))
		.addCatalyst(0, ModItems.ENCHANTED_PETAL.get())
		.addCatalyst(2, Items.QUARTZ)
		.addCatalyst(4, Items.GLOWSTONE_DUST)
		.addCatalyst(6, Items.QUARTZ)
		.addCatalyst(1, Items.LAPIS_LAZULI)
		.addCatalyst(3, Items.LAPIS_LAZULI)
		.addCatalyst(5, Items.LAPIS_LAZULI)
		.addCatalyst(7, Items.LAPIS_LAZULI)
		.setGroup("enchantment")
		.setTime(300)
		.build();
	    
		InfusionRecipe.Builder.create("piercing_book")
		.setInput(Items.BOOK)
		.setOutput(createEnchantedBook(Enchantments.PIERCING, 1))
		.addCatalyst(0, ModItems.ENCHANTED_PETAL.get())
		.addCatalyst(2, Items.GLOWSTONE_DUST)
		.addCatalyst(4, Items.SPECTRAL_ARROW)
		.addCatalyst(6, Items.GLOWSTONE_DUST)
		.addCatalyst(1, Items.LAPIS_LAZULI)
		.addCatalyst(3, Items.LAPIS_LAZULI)
		.addCatalyst(5, Items.LAPIS_LAZULI)
		.addCatalyst(7, Items.LAPIS_LAZULI)
		.setGroup("enchantment")
		.setTime(300)
		.build();
	    
		InfusionRecipe.Builder.create("mending_book")
		.setInput(Items.BOOK)
		.setOutput(createEnchantedBook(Enchantments.MENDING, 1))
		.addCatalyst(0, ModItems.ENCHANTED_PETAL.get())
		.addCatalyst(2, Items.EXPERIENCE_BOTTLE)
		.addCatalyst(4, Blocks.ANVIL)
		.addCatalyst(6, Items.EXPERIENCE_BOTTLE)
		.addCatalyst(1, Items.LAPIS_LAZULI)
		.addCatalyst(3, Items.LAPIS_LAZULI)
		.addCatalyst(5, Items.LAPIS_LAZULI)
		.addCatalyst(7, Items.LAPIS_LAZULI)
		.setGroup("enchantment")
		.setTime(375)
		.build();
	}
	
	private static ItemStack createEnchantedBook(Enchantment enchantment, int level) 
	{
		ItemStack book = new ItemStack(Items.ENCHANTED_BOOK);
		EnchantedBookItem.addEnchantment(book, new EnchantmentData(enchantment, level));
		return book;
	}
}
